name: CI

on:
    push:
    pull_request:

jobs:
    build:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Pull images
              run: docker compose pull
            - name: Build services
              run: docker compose build  --build-arg USER_GID=$(id -u) --build-arg USER_UID=$(id -g)
            - name: Start services
              run: docker compose up -d
            - name: Install project
              run: docker exec similaritipsum-php-1 composer install
            - name: Run tests
              run: docker exec similaritipsum-php-1 bin/phpunit
            - name: Check HTTP reachability
              run: curl http://localhost:8050
